[repository]
name = "hyprstep"
authors = ["syuzuki"]
commit_pins = [
  ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "1.0.0"], # 0.48.1
]

[hyprstep]
description = "Add additional monitor specifier to find by the positions"
authors = ["syuzuki"]
output = "build/hyprstep.so"
build = [
  "meson setup build --wipe",
  "ninja -C build",
]
