[repository]
name = "hyprstep"
authors = ["syuzuki"]
commit_pins = [
  ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "1.0.0"], # 0.48.1
  ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "2.0.0"], # 0.49.0
  ["c4a4c341568944bd4fb9cd503558b2de602c0213", "2.0.0"], # 0.50.0
]

[hyprstep]
description = "Add additional monitor specifier to find by the positions"
authors = ["syuzuki"]
output = "build/hyprstep.so"
build = [
  "meson setup build --wipe",
  "ninja -C build",
]
